### ISSUE TITLE
Keep EuHealthCert simple

### ISSUE THREAD

**Issue by DKvarn** [ehn-dcc-development/ValidationCore#20]
Functionality for text presentation have been added to EuHealtCert and to have ValidationCore as a library the functions for presentation should not be in the library, presentation should be handled in the main app. For example we will fetch and update the ValueSets from the client app so we don't need to make a new release every time a new value are added, therefore this presentation functionality wont be used and are just adding complexity. 

I suggest DGCValueSets.swift should be moved to the app and should not be in the library, so for example Recovery.disease should be changed back to String.

**Comment by asitdm** [comment]
Hi, we discussed this internally and came to the conclusion, that it would indeed be a better way to handle the value sets in the application itself. The changes will be in the next commit.

**Comment by asitdm** [comment]
Changes are pushed to the main branch.
